# Generated by Django 6.0.1 on 2026-02-24 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('About_Idoingreece_description', models.TextField()),
                ('About_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('About_Idoingreece_img', models.ImageField(upload_to='About_images/')),
                ('About_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('About_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-About_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='ExcellenceIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Excellence_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Excellence_Idoingreece_description', models.TextField()),
                ('Excellence_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Excellence_Idoingreece_img', models.ImageField(upload_to='Excellence_images/')),
                ('Excellence_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Excellence_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Excellence_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Feature2_IdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature2_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Feature2_Idoingreece_status', models.CharField(blank=True, max_length=255, null=True)),
                ('Feature2_Idoingreece_description', models.TextField()),
                ('Feature2_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Feature2_Idoingreece_img', models.ImageField(upload_to='Feature2_images/')),
                ('Feature2_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Feature2_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Feature2_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='FeatureIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Feature_Idoingreece_status', models.CharField(blank=True, max_length=255, null=True)),
                ('Feature_Idoingreece_description', models.TextField()),
                ('Feature_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Feature_Idoingreece_img', models.ImageField(upload_to='Feature_images/')),
                ('Feature_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Feature_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Feature_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='FirstIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('First_Idoingreece_description', models.TextField()),
                ('First_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('First_Idoingreece_img', models.ImageField(upload_to=' First_images/')),
                ('First_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('First_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-First_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='IdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Idoingreece_description', models.TextField()),
                ('Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Idoingreece_img', models.ImageField(upload_to='idoingreece_images/')),
                ('Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='NotifyNewsIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotifyNews_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('NotifyNews_Idoingreece_description', models.TextField()),
                ('NotifyNews_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('NotifyNews_Idoingreece_img', models.ImageField(upload_to='NotifyNews_images/')),
                ('NotifyNews_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('NotifyNews_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-NotifyNews_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SecondIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Second_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Second_Idoingreece_description', models.TextField()),
                ('Second_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Second_Idoingreece_img', models.ImageField(upload_to='Second_idoingreece_images/')),
                ('Second_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Second_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Second_Idoingreece_publish_date'],
            },
        ),
    ]
