# Generated by Django 6.0.1 on 2026-02-25 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('About_Idoingreece_description', models.TextField()),
                ('About_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('About_Idoingreece_img', models.ImageField(upload_to='About_images/')),
                ('About_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('About_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-About_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('blog_image', models.ImageField(upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExcellenceIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Excellence_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Excellence_Idoingreece_description', models.TextField()),
                ('Excellence_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Excellence_Idoingreece_img', models.ImageField(upload_to='Excellence_images/')),
                ('Excellence_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Excellence_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Excellence_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionalIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exceptional_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Exceptional_Idoingreece_status', models.CharField(blank=True, max_length=255, null=True)),
                ('Exceptional_Idoingreece_description', models.TextField()),
                ('Exceptional_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Exceptional_Idoingreece_img', models.ImageField(upload_to='Exceptional_images/')),
                ('Exceptional_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Exceptional_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Exceptional_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Feature2_IdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature2_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Feature2_Idoingreece_status', models.CharField(blank=True, max_length=255, null=True)),
                ('Feature2_Idoingreece_description', models.TextField()),
                ('Feature2_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Feature2_Idoingreece_img', models.ImageField(upload_to='Feature2_images/')),
                ('Feature2_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Feature2_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Feature2_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='FirstIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('First_Idoingreece_description', models.TextField()),
                ('First_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('First_Idoingreece_img', models.ImageField(upload_to=' First_images/')),
                ('First_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('First_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-First_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='IdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Idoingreece_description', models.TextField()),
                ('Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Idoingreece_img', models.ImageField(upload_to='idoingreece_images/')),
                ('Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='NotifyNewsIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotifyNews_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('NotifyNews_Idoingreece_description', models.TextField()),
                ('NotifyNews_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('NotifyNews_Idoingreece_img', models.ImageField(upload_to='NotifyNews_images/')),
                ('NotifyNews_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('NotifyNews_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-NotifyNews_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SecondIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Second_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Second_Idoingreece_description', models.TextField()),
                ('Second_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Second_Idoingreece_img', models.ImageField(upload_to='Second_idoingreece_images/')),
                ('Second_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Second_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Second_Idoingreece_publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField()),
                ('services', models.TextField()),
                ('languages', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('listing_type', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='idoingreece.category')),
                ('locations', models.ManyToManyField(to='idoingreece.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idoingreece.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendors/')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='idoingreece.vendor')),
            ],
        ),
    ]
