# Generated by Django 6.0.1 on 2026-03-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='notifynewsidoingreecepost',
            name='NotifyNews_Idoingreece_author',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_at',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='secondidoingreecepost',
            name='Second_Idoingreece_img',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('Real Weddings', 'Real Weddings'), ('Planning Guides', 'Planning Guides'), ('Inspiration', 'Inspiration'), ('Trends', 'Trends'), ('Vendor Spotlights', 'Vendor Spotlights')], max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secondidoingreecepost',
            name='Second_Idoingreece_video',
            field=models.FileField(blank=True, null=True, upload_to='Second_idoingreece_video/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ExceptionalIdoingreecePost',
        ),
        migrations.DeleteModel(
            name='NotifyNewsIdoingreecePost',
        ),
    ]
