# Generated by Django 6.0.1 on 2026-02-24 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionalIdoingreecePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exceptional_Idoingreece_title', models.CharField(blank=True, max_length=255, null=True)),
                ('Exceptional_Idoingreece_status', models.CharField(blank=True, max_length=255, null=True)),
                ('Exceptional_Idoingreece_description', models.TextField()),
                ('Exceptional_Idoingreece_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('Exceptional_Idoingreece_img', models.ImageField(upload_to='Exceptional_images/')),
                ('Exceptional_Idoingreece_publish_date', models.DateTimeField(auto_now_add=True)),
                ('Exceptional_Idoingreece_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-Exceptional_Idoingreece_publish_date'],
            },
        ),
        migrations.DeleteModel(
            name='FeatureIdoingreecePost',
        ),
    ]
