# Generated by Django 6.0.1 on 2026-02-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0002_contactmessage_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_at',
            new_name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
