# Generated by Django 6.0.1 on 2026-03-16 23:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0002_contactmessage_newslettersubscriber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutidoingreecepost',
            name='About_Idoingreece_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='About_images/'),
        ),
        migrations.AlterField(
            model_name='adzone',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='ads/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='blog_images/'),
        ),
        migrations.AlterField(
            model_name='excellenceidoingreecepost',
            name='Excellence_Idoingreece_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Excellence_images/'),
        ),
        migrations.AlterField(
            model_name='feature2_idoingreecepost',
            name='Feature2_Idoingreece_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Feature2_images/'),
        ),
        migrations.AlterField(
            model_name='firstidoingreecepost',
            name='First_Idoingreece_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='First_images/'),
        ),
        migrations.AlterField(
            model_name='idoingreecepost',
            name='Idoingreece_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondidoingreecepost',
            name='Second_Idoingreece_video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Second_idoingreece_video/'),
        ),
        migrations.AlterField(
            model_name='vendorimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='vendors/'),
        ),
    ]
