# Generated by Django 6.0.1 on 2026-02-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0003_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('weddings', 'Weddings'), ('events', 'Events'), ('tips', 'Tips & Advice'), ('planning', 'Planning')], max_length=50),
        ),
    ]
