# Generated by Django 6.0.1 on 2026-03-16 23:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0003_alter_aboutidoingreecepost_about_idoingreece_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoingreecepost',
            name='Idoingreece_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='idoingreece_images/'),
        ),
    ]
