# Generated by Django 6.0.1 on 2026-02-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0004_alter_blogpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='summary',
        ),
    ]
