# Generated by Django 6.0.1 on 2026-03-17 15:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0005_alter_aboutidoingreecepost_about_idoingreece_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondidoingreecepost',
            name='Second_Idoingreece_video',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
