# Generated by Django 6.0.1 on 2026-02-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0005_remove_blogpost_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, choices=[('Real Weddings', 'Real Weddings'), ('Planning Guides', 'Planning Guides'), ('Inspiration', 'Inspiration'), ('Trends', 'Trends'), ('Vendor Spotlights', 'Vendor Spotlights')], max_length=50),
        ),
    ]
