# Generated by Django 6.0.1 on 2026-03-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0006_alter_blogpost_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotifyNewsIdoingreecePost',
        ),
    ]
