# Generated by Django 6.0.1 on 2026-03-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0007_delete_notifynewsidoingreecepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondidoingreecepost',
            name='Second_Idoingreece_img',
        ),
        migrations.AddField(
            model_name='secondidoingreecepost',
            name='Second_Idoingreece_video',
            field=models.FileField(blank=True, null=True, upload_to='Second_idoingreece_video/'),
        ),
    ]
