# Generated by Django 6.0.1 on 2026-03-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0008_remove_secondidoingreecepost_second_idoingreece_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couple_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('wedding_location', models.CharField(max_length=200)),
                ('wedding_date', models.DateField()),
                ('story', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
