# Generated by Django 6.0.1 on 2026-03-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idoingreece', '0009_weddingstory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeddingStory',
        ),
    ]
