# Generated by Django 6.0.1 on 2026-03-16 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('Planner', 'Planner'), ('Venue', 'Venue'), ('Florist', 'Florist'), ('Photographer', 'Photographer'), ('Videographer', 'Videographer'), ('DJ & Entertainment', 'DJ & Entertainment'), ('Hair & Makeup', 'Hair & Makeup'), ('Catering', 'Catering'), ('Wedding Cake', 'Wedding Cake'), ('Transport', 'Transport'), ('Officiant', 'Officiant'), ('Accommodation', 'Accommodation'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_profiles/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bio',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendorprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VendorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_gallery/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='accounts.vendorprofile')),
            ],
        ),
    ]
