# Generated by Django 6.0.1 on 2026-03-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vendorprofile_age_vendorprofile_county_of_residence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
