# Generated by Django 6.0.1 on 2026-03-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vendorprofile_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='subscription_expires',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10),
        ),
    ]
