# Generated by Django 6.0.1 on 2026-03-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_vendorprofile_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('Planner', 'Planner'), ('Venue', 'Venue'), ('Florist', 'Florist'), ('Photographer', 'Photographer'), ('Videographer', 'Videographer'), ('DJ & Entertainment', 'DJ & Entertainment'), ('Hair & Makeup', 'Hair & Makeup'), ('Catering', 'Catering'), ('Wedding Cake', 'Wedding Cake'), ('Transport', 'Transport'), ('Officiant', 'Officiant'), ('Accommodation', 'Accommodation'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
