# Generated by Django 6.0.1 on 2026-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_vendorprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='bio',
            field=models.CharField(max_length=250),
        ),
    ]
