# Generated by Django 6.0.1 on 2026-03-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_vendorprofile_age_remove_vendorprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='county_of_residence',
        ),
    ]
