# Generated by Django 6.0.1 on 2026-03-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_vendorprofile_county_of_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
    ]
