# Generated by Django 6.0.1 on 2026-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_vendorprofile_facebook_vendorprofile_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='bio',
            field=models.CharField(max_length=1000),
        ),
    ]
